/*
 * Copyright 2025 RDK Management — Apache-2.0
 *
 * ai_diag_workflow.c — iterative LLM-driven diagnostic loop
 *
 * Workflow overview
 * ─────────────────
 *   1. Build Turn-1 content (anomaly notification + key metrics).
 *   2. Send to LLM via ai_diag_llm_call().
 *   3. If response.status == NEED_DATA:
 *        a. Execute each next_command through ai_diag_cmd_run_batch().
 *        b. Build Turn-N followup content with command outputs.
 *        c. Go to step 2 (up to cfg->max_turns times).
 *   4. If response.status == ANALYSIS_COMPLETE:
 *        a. Log suspected_issue, confidence, and recommended_action.
 *        b. Exit the loop.
 *   5. If max_turns is reached: log a warning and exit.
 *
 * The system prompt instructs the LLM to respond only in well-structured JSON,
 * which the parser in ai_diag_json.c knows how to consume.
 */

#include "ai_diag_workflow.h"
#include "ai_diag_cmd.h"
#include "ai_diag_json.h"
#include "ai_diag_llm.h"
#include "ai_diag_log.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>

/* ── System prompt ───────────────────────────────────────────────────────── */
/*
 * Identical in structure to the prompt used in example.txt; extended to
 * support memory and combined CPU+memory anomaly types, and to accept the
 * structured JSON command-output format generated by this workflow.
 */
// static const char g_system_prompt[] =
//     "You are an embedded device diagnostic assistant for RDK-B broadband "
//     "devices. Your job is to guide anomaly debugging step-by-step. "
//     "Rules: "
//     "Keep responses extremely short and precise. "
//     "Respond ONLY in JSON format. "
//     "Do not provide explanations. "
//     "Do not provide unwanted text. "
//     "Request only required commands or logs. "
//     "Focus only on Linux/RDK-B diagnostics. "
//     "Commands must be executable on embedded Linux systems. "
//     "When given command outputs in commands_executed array, analyse them "
//     "before requesting more data. "
//     "If enough data is available, provide suspected_issue, confidence, and "
//     "recommended_action. "
//     "If more data is needed, provide next_commands. "
//     "Never ask conversational questions. "
//     "Never use markdown formatting. "
//     "Never include code blocks. "
//     "Response format — "
//     "If more data is needed: "
//     "{\"status\":\"need_data\",\"next_commands\":[\"command1\",\"command2\"]} "
//     "If analysis is complete: "
//     "{\"status\":\"analysis_complete\","
//     "\"suspected_issue\":\"short_issue_name\","
//     "\"confidence\":\"high|medium|low\","
//     "\"recommended_action\":[\"action1\",\"action2\"]}";

static const char g_system_prompt[] =
"You are an embedded device diagnostic assistant for RDK-B broadband "
"devices. Your job is to guide anomaly debugging step-by-step. "
"Rules: "
"Keep responses extremely short and precise. "
"Respond ONLY in JSON format. "
"Do not provide explanations. "
"Do not provide unwanted text. "
"Request only required commands or logs. "
"Focus only on Linux/RDK-B diagnostics. "

"RDK-B devices support only BusyBox-compatible shell commands and "
"utilities. "
"Do not use bash-specific syntax, python, perl, awk scripts requiring "
"GNU extensions, or non-embedded Linux tools. "
"Commands must work on lightweight embedded Linux environments. "

"BusyBox ps does NOT support the -o option. "
"Do not use 'ps -o' in any form. "
"Use 'ps' or 'ps w' for process listing instead. "

"logread may fail with 'can't find syslogd buffer' on this device. "
"Do not retry logread if it has already returned no data. "

"Prefer low-overhead diagnostic commands. "
"Avoid commands that consume high CPU, high memory, or generate large "
"outputs. "
"Avoid infinite loops, interactive commands, background jobs, or "
"commands requiring user interaction. "

"Prefer RDK-B utilities when available, including dmcli, wifi_api, "
"sysevent, syscfg, logread, and /proc interfaces. "

"When given command outputs in commands_executed array, analyse them "
"before requesting more data. "

"Do not repeatedly request the same commands if sufficient data is "
"already available. "

"If enough data is available, provide suspected_issue, confidence, and "
"recommended_action. "

"If more data is needed, provide next_commands. "

"Never ask conversational questions. "
"Never use markdown formatting. "
"Never include code blocks. "

"All responses must be valid compact JSON. "
"Do not include newline characters outside JSON strings. "

"Response format — "

"If more data is needed: "
"{\"status\":\"need_data\","
"\"next_commands\":[\"command1\",\"command2\"]} "

"If analysis is complete: "
"{\"status\":\"analysis_complete\","
"\"suspected_issue\":\"short_issue_name\","
"\"confidence\":\"high|medium|low\","
"\"recommended_action\":[\"action1\",\"action2\"]}";

/*
 * Forced-final system prompt: used when max_turns is exhausted.
 * The LLM is required to respond with analysis_complete — need_data is
 * not accepted.  Confidence should be set to "low" when data was limited.
 */
static const char g_system_prompt_final[] =
"You are an embedded device diagnostic assistant for RDK-B broadband "
"devices. "
"The maximum number of diagnostic turns has been reached. "
"You MUST respond with status 'analysis_complete'. "
"Do NOT use status 'need_data'. "
"Do NOT request any more commands. "
"Based on the anomaly type and severity provided, give your best-effort "
"diagnosis. Set confidence to 'low' if data was insufficient. "
"Respond ONLY in valid compact JSON: "
"{\"status\":\"analysis_complete\","
"\"suspected_issue\":\"short_issue_name\","
"\"confidence\":\"high|medium|low\","
"\"recommended_action\":[\"action1\",\"action2\"]}";


/* ── Internal helpers ────────────────────────────────────────────────────── */

static void log_result(const AnomalyEvent *event, const LlmResponse *resp)
{
    AiDiagInfo("=== DIAGNOSTIC COMPLETE ===");
    AiDiagInfo("MAC: %s  Timestamp: %s  AnomalyType: %s",
               event->mac, event->timestamp,
               ai_anomaly_label(event->anomaly_type));
    AiDiagInfo("Suspected issue : %s", resp->suspected_issue);
    AiDiagInfo("Confidence      : %s", resp->confidence);
    for (int i = 0; i < resp->num_actions; i++)
        AiDiagInfo("Action [%d/%d]    : %s",
                   i + 1, resp->num_actions, resp->recommended_action[i]);
    AiDiagInfo("===========================");
}

static void log_turn(int turn, const LlmResponse *resp)
{
    if (resp->status == LLM_STATUS_NEED_DATA) {
        AiDiagInfo("Turn %d: LLM needs %d more command(s)",
                   turn, resp->num_commands);
        for (int i = 0; i < resp->num_commands; i++)
            AiDiagInfo("  next_cmd[%d]: %s", i, resp->next_commands[i]);
    }
}

/* ── ai_diag_workflow_run ────────────────────────────────────────────────── */

int ai_diag_workflow_run(const AnomalyEvent *event, const AiDiagConfig *cfg)
{
    AiDiagInfo("workflow_run: start  MAC=%s type=%s  CPU_SEV=%.2fx MEM_SEV=%.2fx",
               event->mac,
               ai_anomaly_label(event->anomaly_type),
               (double)event->cpu_sev,
               (double)event->mem_sev);

    int  ret      = -1;
    int  turn     = 0;
    char *content = NULL;
    char *request = NULL;

    /* Per-turn command output storage */
    const char *cmds_ptr[AI_DIAG_MAX_COMMANDS];
    char       *cmd_outputs[AI_DIAG_MAX_COMMANDS];
    memset(cmd_outputs, 0, sizeof(cmd_outputs));

    LlmResponse resp;
    memset(&resp, 0, sizeof(resp));

    /* ── Turn 1: initial anomaly notification ──────────────────────────── */
    turn = 1;
    content = ai_diag_build_initial_content(event);
    if (!content) {
        AiDiagError("workflow_run: failed to build initial content");
        goto done;
    }

    AiDiagInfo("Turn %d: sending initial anomaly notification", turn);

    for (;;) {
        /* Build and send request */
        request = ai_diag_build_request(cfg, g_system_prompt, content);
        free(content);
        content = NULL;

        if (!request) {
            AiDiagError("workflow_run: failed to build request (turn %d)", turn);
            goto done;
        }

        AiDiagDebug("workflow_run: turn %d request body length: %zu",
                    turn, strlen(request));

        int llm_rc = ai_diag_llm_call(cfg, request, &resp);
        free(request);
        request = NULL;

        if (llm_rc != 0) {
            AiDiagError("workflow_run: LLM call failed on turn %d", turn);
            goto done;
        }

        log_turn(turn, &resp);

        /* ── Terminal condition: analysis complete ─────────────────────── */
        if (resp.status == LLM_STATUS_ANALYSIS_COMPLETE) {
            log_result(event, &resp);
            ai_diag_execute_actions(&resp);
            ret = 0;
            goto done;
        }

        /* ── Check loop bounds ────────────────────────────────────────── */
        if (turn >= cfg->max_turns) {
            AiDiagWarn("workflow_run: max turns (%d) reached, attempting "
                       "forced final analysis for MAC=%s",
                       cfg->max_turns, event->mac);

            /* One extra LLM call with a stricter prompt that forbids
             * need_data, forcing a best-effort analysis_complete. */
            content = ai_diag_build_forced_final_content(event);
            if (!content) {
                AiDiagError("workflow_run: failed to build forced final content");
                goto done;
            }

            request = ai_diag_build_request(cfg, g_system_prompt_final, content);
            free(content);
            content = NULL;

            if (!request) {
                AiDiagError("workflow_run: failed to build forced final request");
                goto done;
            }

            AiDiagInfo("workflow_run: forced final turn (after turn %d)", turn);

            int forced_rc = ai_diag_llm_call(cfg, request, &resp);
            free(request);
            request = NULL;

            if (forced_rc == 0 && resp.status == LLM_STATUS_ANALYSIS_COMPLETE) {
                log_result(event, &resp);
                ai_diag_execute_actions(&resp);
                ret = 0;
            } else {
                AiDiagWarn("workflow_run: forced final did not produce "
                           "analysis_complete for MAC=%s", event->mac);
            }
            goto done;
        }

        if (resp.num_commands == 0) {
            AiDiagWarn("workflow_run: need_data but no commands returned "
                       "(turn %d)", turn);
            goto done;
        }

        /* ── Execute requested commands ───────────────────────────────── */
        turn++;
        AiDiagInfo("Turn %d: executing %d diagnostic command(s)",
                   turn, resp.num_commands);

        for (int i = 0; i < resp.num_commands; i++)
            cmds_ptr[i] = resp.next_commands[i];

        /* Free previous round's outputs */
        for (int i = 0; i < AI_DIAG_MAX_COMMANDS; i++) {
            free(cmd_outputs[i]);
            cmd_outputs[i] = NULL;
        }

        ai_diag_cmd_run_batch(cmds_ptr, cmd_outputs,
                              resp.num_commands, cfg->cmd_timeout_sec);

        /* ── Build followup content ────────────────────────────────────── */
        content = ai_diag_build_followup_content(
                      event, turn,
                      cmds_ptr,
                      (const char * const *)cmd_outputs,
                      resp.num_commands);

        if (!content) {
            AiDiagError("workflow_run: failed to build followup content "
                        "(turn %d)", turn);
            goto done;
        }
    }

done:
    free(content);
    free(request);
    for (int i = 0; i < AI_DIAG_MAX_COMMANDS; i++)
        free(cmd_outputs[i]);

    AiDiagInfo("workflow_run: end  MAC=%s  result=%s",
               event->mac, ret == 0 ? "analysis_complete" : "incomplete");
    return ret;
}

/* ── ai_diag_workflow_thread ─────────────────────────────────────────────── */

void *ai_diag_workflow_thread(void *args)
{
    WorkflowArgs *wa = (WorkflowArgs *)args;
    if (!wa)
        return NULL;

    ai_diag_workflow_run(&wa->event, &wa->cfg);
    free(wa);
    return NULL;
}
