/*
 * Copyright 2025 RDK Management — Apache-2.0
 *
 * ai_diag_log.c — thread-safe file-based logging implementation
 */

#include "ai_diag_log.h"

#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <pthread.h>

static char            g_log_path[256] = AI_DIAG_LOG_PATH;
static pthread_mutex_t g_log_mtx       = PTHREAD_MUTEX_INITIALIZER;

void ai_diag_log_init(const char *log_path)
{
    if (!log_path || !*log_path)
        return;

    pthread_mutex_lock(&g_log_mtx);
    strncpy(g_log_path, log_path, sizeof(g_log_path) - 1);
    g_log_path[sizeof(g_log_path) - 1] = '\0';
    pthread_mutex_unlock(&g_log_mtx);
}

void ai_diag_log_write(const char *level, const char *fmt, ...)
{
    /* Format the message into a stack buffer first so we hold the mutex
     * for the shortest possible time. 2 KiB is sufficient for all
     * diagnostic messages generated by this module. */
    char msg[2048];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(msg, sizeof(msg), fmt, ap);
    va_end(ap);

    /* Timestamp */
    time_t now = time(NULL);
    struct tm tm_info;
    localtime_r(&now, &tm_info);
    char ts[32];
    strftime(ts, sizeof(ts), "%Y-%m-%d %H:%M:%S", &tm_info);

    pthread_mutex_lock(&g_log_mtx);

    FILE *fp = fopen(g_log_path, "a");
    if (!fp)
        fp = stderr;        /* fallback: stderr is always available */

    fprintf(fp, "%s [AI_DIAG][%s] %s\n", ts, level, msg);
    fflush(fp);

    if (fp != stderr)
        fclose(fp);

    pthread_mutex_unlock(&g_log_mtx);
}
